baseURL = "https://soonernotfaster.com/"
languageCode = "en-us"
title = "Steven Solomon"

googleAnalytics = "G-62XB0Z5ZK6"
enableRobotsTXT = true
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
pygmentsCodeFences = true

[params]
  custom_css = ["css/custom-v1.01.css"]
  twitter = "https://twitter.com/soonernotfaster"
  linkedin = "https://www.linkedin.com/in/steven-solomon-86745a24/"
  commentoEnable = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]

[[menu.main]]
    identifier = "learn tdd"
    name = "learn tdd"
    title = "all about Steven Solomon"
    url = "https://www.manning.com/liveprojectseries/tdd-for-a-shopping-web-site?utm_source=solomons&utm_medium=affiliate&utm_campaign=liveproject_solomon_tdd_12_21_21&a_aid=solomons&a_bid=175986d2"
    weight = -110

[[menu.main]]
    identifier = "about"
    name = "about me"
    title = "all about Steven Solomon"
    url = "/about/"
    weight = -110

[[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/"
    weight = -110

[[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = -110
