baseURL = "https://soonernotfaster.com/"
languageCode = "en-us"
title = "Steven Solomon"

googleAnalytics = "UA-147621399-1"
enableRobotsTXT = true
theme = "ananke"
pygmentsCodeFences = true

[params]
  custom_css = ["css/custom-v1.01.css"]
  twitter = "https://twitter.com/soonernotfaster"
  linkedin = "https://www.linkedin.com/in/steven-solomon-86745a24/"
  commentoEnable = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]

[[menu.main]]
    identifier = "about"
    name = "about me"
    title = "all about Steven Solomon"
    url = "/about/"
    weight = -110

[[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/"
    weight = -110

[[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = -110
